services:
  backend1:
    build: !reset null
    image: ghcr.io/mahendramahato/i_play/backend:latest
  backend2:
    build: !reset null
    image: ghcr.io/mahendramahato/i_play/backend:latest
  backend3:
    build: !reset null
    image: ghcr.io/mahendramahato/i_play/backend:latest
  frontend:
    build: !reset null
    image: ghcr.io/mahendramahato/i_play/frontend:latest